### ISSUE TITLE
Endless provisioning new containers if previous container failed to launch

### ISSUE THREAD

**Issue by recyard** [jenkinsci/docker-plugin#136]
When a container failed to be launched in a build, another container with different id will be launched.

Considering this case, if a docker image is faulty and container will definitely fail on launching, numerous new containers will be launched (and failed) until reaching the instance cap, if cap is not set, this creating new container process will  be endless, which consumes large resources on slave connection retry and makes Jenkins very slow.

This should be avoided or at least configurable for a user to choose whether use only one container for one build, or whether to retry on a container startup failure.

This is a major setback for using in production env.

**Comment by thomassuckow** [comment]
Jenkins decides when to start a new container. The fact that it sounds like the container does not get destroyed when I assume the docker plugin removes the slave is a sign of a bigger issue. Is that an accurate understanding of what you are seeing?

While it may be useful to flag a container as "bad" if it fails to start, I could see this also becoming annoying in false positives. Especially since people seem to already be having issues where it takes several tries for the slave to start correctly.

If my first statement was fixed, it should be reasonable for it to try and spin up slaves over and over. Though if there is a large backlog wanting the same container, it may end up where jenkins never asks for other containers. But I imagine a simliar issue would be present with EC2 as well.

**Comment by recyard** [comment]
Well the containers do get destroyed after the idle time, the problem is as long as the jenkins build waiting for an available container is not aborted, new containers will be spawned and fail one by one in Jenkins. I think it is common when we are tunning this plugin with configs, but use a docker image that fails to launch the container correctly. In this case I don't see starting a new container will be helpful, because it surely fails as well, and the downside it brings is obvious, Jenkins becomes quite slow until some action like aborting the build is taken.

I open this issue because I see someone else is also troubled, he posted a comment on the plugin wiki page of Jenkins site, maybe didn't get noticed.

**Comment by thomassuckow** [comment]
I certainly didn't notice.
https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin?focusedCommentId=75431984#comment-75431984

This may still be worth implementing at some point, though with the ability to turn it off. It would also need a way to "reset" the bad flag if you update the container.

I am still surprised that it is bogging down the Jenkins master. Is docker on the same machine and the containers are overtaxing the system?

**Comment by jspiewak** [comment]
It definitely bogs down the master if you have set an instance cap. Once the cap is hit with these bad containers, jobs that require that type of container queue up and don't run. I have to regularly kill these bad containers in order to keep things flowing.

I haven't figured out if it is related yet, but I am using the SSH Agent plugin as well in order to provide credentials and I find that it creates an unlimited number of agent threads that never die, leading over time to an out of memory situation.

**Comment by recyard** [comment]
I set the instance cap to 4 so only 4 containers are started and then failed, but since then Jenkins got very slow and even went dead once. This should not be a docker issue but on Jenkins side.

Another related issue I see today makes me realize a not very proper cloud node provisioning strategy on Jenkins. Say I have job1 (multijob type) and job2 (freestyle), both run on the same label of docker slave, job1 runs and triggers job2, but job1 will not finish until job2 finishes. In this case, job2 will wait for job1's container executor to be available for 2 minutes, then it starts another container. It suprises me because job2 doesn't start its own container instantly when it's triggered, but waiting for a running one.

The feature I really want and I think is suitable for many users is that: for every build of any job, one and only one new container is started immediately, if it's started successfully, then good, if not, this build will fail fast but not waiting for new containers.

**Comment by thomassuckow** [comment]
Unfortunately **when** a cloud slave is started is decided by Jenkins all on its own. I once saw a message on the Jenkins mailing list discussing making and alternative scheduler that was more aggressive that could optionally replace the built in one. Nothing ever appeared to come of it.

**Comment by magnayn** [comment]
Perhaps the default (if you don't specify) instance cap ought to be 1 ?

**Comment by recyard** [comment]
Yea, setting the cap to 1 is the only workround I can figure out to test a docker image.

For the container provisioning strategy, I guess it's highly restricted by the default NodeProvisioner which is not suitable for cloud slaves, not sure if the plugin can use a customized provisioner that does not wait for the availability of existing container executors.
