### ISSUE TITLE
Feature request: multiple "Volumes From"

### ISSUE THREAD

**Issue by bartmeuris** [jenkinsci/docker-plugin#160]
Currently you can only use volumes from 1 other container when specifying the "Volumes From", it would be nice if you could add more than one here.

**Comment by jan-mueller-work** [comment]
+1

**Comment by flandr** [comment]
This looks like it is blocked on intaking multi-volumes-from support from docker-java/docker-java@48ba911ee7c9c6ff834dcd839f9a3abc5d9ddc4c, which will in turn depend on outstanding patches from docker-java/docker-java#146 getting merged. Happy to provide a patch for this once the outstanding dependencies have been merged; otherwise development can be a bit painful.

**Comment by KostyaSha** [comment]
Seems this functionality already available for testing, let's continue to #183

**Comment by maafy6** [comment]
I don't see why this was closed, these are two different issues, and #183 does nothing to address this.
