### ISSUE TITLE
Plugin inspects containers once per second causing high load

### ISSUE THREAD

**Issue by thomassuckow** [jenkinsci/docker-plugin#165]
I noticed today the docker plugin polls active containers once a second. When there is a large number of containers, this creates a considerable load on the docker server and also appears to create a considerable load on Jenkins making it less responsive.

It seems to be part of some check that the slave is still alive. If this check originates from Jenkins we should probably either cache this or find a lighter weight check. I would hope there is a way to check the ssh connection status.

```
Feb 25 23:26:44 coreos2 dockerd[681]: time="2015-02-25T23:26:44Z" level="info" msg="GET /containers/c...e/json"
```

**Comment by KostyaSha** [comment]
Or docker should cache it...

**Comment by hawky-4s-** [comment]
The culprit is this check at https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/DockerComputer.java#L93 . We discovered this while using Jenkins on EC2 cloud and 2 configured DockerClouds each running 4 containers. It really kills the responsiveness.

**Comment by magnayn** [comment]
Hm. I've actually thought about this previously. I think what would be
beneficial is a background status-updater object that stuff like this can
use. I.E: something that just does a round-robin poll of the various
hosts/slaves and keeps a table of active/inactive.

Because the Jenkins UI makes synchronous calls to the cloud plugins, if a
host is (say) down or responding slowly it can lock up and make the UI
unresponsive..

**Comment by KostyaSha** [comment]
PeriodicWork and share/cache states throw docker descriptor?

**Comment by magnayn** [comment]
Actually, thinking about it, if it's this check

```java
            } else if( !node.containerExistsInCloud() ) {
                setAcceptingTasks(false);
            }
```

Then it could just cache the response, and re-use it if it's asked within a certain number of ms.

I may try this locally to see if it works.

**Comment by hawky-4s-** [comment]
Hi,

actually we just removed the whole method on our branch and it works without any problems for us. We are running a docker swarm with 5 hosts and different machine specs.
Do you still know what the initial intention was when you overrode the method?

**Comment by thomassuckow** [comment]
@hawky-4s- has a point. The ssh slave probably adequately handles whether the container has disappeared.

**Comment by magnayn** [comment]
I *think* it's because the retention strategy wasn't (isn't?) working correctly when SSH slaves are slow to start.

Maybe requires some experimentation.

**Comment by KostyaSha** [comment]
I hope this will be fixed in #234 . I removed this override and see no issues. I think performance can be optimized after everything will functioning right.

**Comment by KostyaSha** [comment]
@thomassuckow how does it work for you now?

**Comment by thomassuckow** [comment]
It is working quite well. The jenkins master shows occasional spikes of minor load, but I can't be sure that is docker and it is well within acceptable limits. 

The docker server is also performing much better with the docker processes consuming <1% cpu with four containers running.

I'm closing. If the issue returns, open a new ticket.
