### ISSUE TITLE
Why the release cycle is so slow?

### ISSUE THREAD

**Issue by lexandro** [jenkinsci/docker-plugin#172]
Most of us hit by the offline/suspended slave issue and other stuff, but the release is not happened since long time. No answer to the requests, looks like this project is not so actively developed. Should we look after an alternate?

**Comment by KostyaSha** [comment]
Because people are busy with fixing this or other issues.

**Comment by KostyaSha** [comment]
We also waited resolution with library patches and dependency errors in jenkins classloader.

**Comment by magnayn** [comment]
cf Slow / Conservative.

Release often and people moan about edge-cases that get broken because few people have tested.
Release less often and people moan about waiting for people to test their installs before promoting a release.

You're not beholden to a plugin's release cycle. This is open source - you can check it out, build it yourself. It would be useful for people to ACK whether the current -master works for them.

I've noticed there's a jenkins 'experimental update center' that I wasn't aware of. I may try to push a version to that.

**Comment by magnayn** [comment]
OK - there is a -beta1 in the 'experimental' repository. Please test and feedback if that works for you.
