### ISSUE TITLE
Feature Request: Login to private docker registry

### ISSUE THREAD

**Issue by jpgxs** [jenkinsci/docker-plugin#184]
Ability to log in to a private docker registry before pulling/pushing an image.

For example, if I am using 'my-private-registry.com/repository:tag' which requires a login.

This would also be helpful when pushing the image after commit (once custom repository names are possible)

**Comment by hawky-4s-** [comment]
@KostyaSha 
I want to contribute this feature to docker-plugin but I am unsure how the configuration should be done:
- One could configure the registry for each template separately together with the login credentials.
- Another approach would be to configure the registries at top and just link them for each template.
- Use some kind of auto detection based on image name which usually includes the registry

WDYT?

**Comment by KostyaSha** [comment]
@hawky-4s- i think as a first step we should add credentials for docker daemon itself. As i see we can add docker-commons dependency, then extend configBuilder that now expects some crazy certificate. 
From credentials viewpoint it probably may work with domain restrictions, but that wouldn't work with multiple pushers for one repo. Seems we should require registry creds in build/publish step and everywhere where push happens.

@hawky-4s- btw i plan split and modularise this code:
- like i made for DockerTemplateBase, create BuildTemplateDescribable/PushTemplateDescribable that will have all push options and method that can fill docker-java push object. 
- client connection should be unbundled and allow chose either existed DockerCloud (clients) either custom i.e. we want make build on non DockerCloud host. 
- BuildPublish step will be tricky because between Build and Publish should be logic that will exclude push in case of errors (probably checkbox that will hide push options).

Let's collect use cases:
- cred is required for pushing in BuildPublish
- cred is required for pulling image in DockerCloud (we should have the way to specify different creds for different hosts, right?)
- cred required to push committed container (for this i found what should be changed and where for commit slave container (during build/after build).

**Comment by KostyaSha** [comment]
<ofttopic>
@hawky-4s- and modular client was also planned for swarm support where you can add restrictions and other features ;)
</offtopic>

**Comment by pgokul** [comment]
+1 for this. We use a private docker repository and have different build images which we need to pull from this private repository. Current approach is to manually pull down the images but it would be great if the plugin could do it.

**Comment by jgriffiths1993** [comment]
btw, credentials are not necessarily required to push or pull containers from a private registry

**Comment by fraz3alpha** [comment]
Has any further attempt been made to work on this feature in this plugin? With more private registry solutions becoming available (and not just the registry image from DockerHub) not being able to authenticate with these is becoming a big sticking point.

I see Kanstantsin has already implemented something in his fork of the plugin: https://github.com/KostyaSha/yet-another-docker-plugin/pull/17/ .

**Comment by magnayn** [comment]
It's in and working in the latest release.

**Comment by magnayn** [comment]
This is currently used in push - it may need to be added for pull if you're
also needing that.

If you look to
https://github.com/jenkinsci/docker-plugin/commit/624ef7519aa9035e9c6a6393a3db6c88af08d0cd

It's mostly a small matter of adding the authconfig to the command required.

**Comment by fraz3alpha** [comment]
Apologies for not being clear, yes pulling the image was what I was referring to -i.e. providing the credentials in the cloud configuration template.

**Comment by ehirsch** [comment]
I just ran into the same issue. I was trying to pull an image from a private repo.

**Comment by fraz3alpha** [comment]
I've successfully pulled an image from a secured (artifactory) docker repository using the latest plugin.
I missed the configuration initially though as it was in a separate section, not with the cloud template where I was expecting it. Check further up, and you can add a repository and credentials  for that URL

**Comment by visibilityspots** [comment]
After adding the private repository in the Docker Plugin section in Configure system of jenkins as indicated by @fraz3alpha , I was able to execute a job on a docker slave from which the image was pulled from a private repository without manual interaction.

Imo this feature request can therefore be closed as well as the jira ticket https://issues.jenkins-ci.org/browse/JENKINS-30668.
