### ISSUE TITLE
How to specify cpuset parameter for docker containers

### ISSUE THREAD

**Issue by mkamlesh** [jenkinsci/docker-plugin#185]
Hi,

I tried setting Docker Command to "--cpusets=0,1 /usr/sbin/sshd -D" so that docker containers launched with this image would have 2 cores assigned to them. But it didn't seem to work. It just kept on spawning one container after other. Inspect revealed that none of them had IP address assigned to them so I guess container initialization process itself was not completed. 

Is this an existing issue or this is not how cpusets or any other docker run parameters are to be specified by docker plugin?

Thanks,
Kamlesh

**Comment by maafy6** [comment]
1. Docker Command only refers to the command run inside the container. You can't pass any docker command line options in. The containers you inspected didn't have an IP address because they tried and then failed to run `--cpusets=0,1 /usr/sbin/sshd -D`.

2. Looks like the docker-java library doesn't support specifying the cpuset option when creating containers. Opened a pull request to add that in (https://github.com/docker-java/docker-java/pull/179), but that would (I think?) also need to make it into @magnayn's branch before the plugin could be updated to allow it.

**Comment by mkamlesh** [comment]
Thanks, maafy6! It would really be great if plugin could support this provision. Looking forward to an updated plugin.

**Comment by KostyaSha** [comment]
Seems this feature was already merged

**Comment by AlexTzib** [comment]
in what filed should I put   --storage-opt ? 
how can I pass other parameters?
