### ISSUE TITLE
Unable to access workspace after build

### ISSUE THREAD

**Issue by nixilla** [jenkinsci/docker-plugin#195]
It may be related to different plugin, but I'd like to ask you first. 

When I run build, I can see files in the workspace. When build is finished the workspace is (not just empty, but) null.

I used the copy-to-slave plugin to copy the contents of the workspace to master. It is working, I can see the files on the master (when I'm logged in via SSH). Somehow Jenkins thinks that workspace is not on the master (in fact it is null).

In normal slave situation, Jenkins would probably access workspace on slave machine and display contents. However Docker container shuts down immediately after build is finished, which makes workspace inaccessible.

1. I cannot access workspace on the container, because it's down.
2. I can copy files to master but Jenkins won't see it.

Is there a way to overcome this issue in this plugin?

FYI, I need to access workspace in order to display reports like coverage, unit test reports, codestyle etc.

**Comment by laetificat** [comment]
You may want to use the `Use custom workspace` option under Advanced in your job configuration and set it to the path where you copy your files to with the copy-to-slave plugin.

**Comment by KostyaSha** [comment]
This is side-affect of using isolated builds, that's why there is ability to share FS to slaves and use mappedFSWorkspace browser.
AFAIR workspace browser searches files only from latest build and node where it was build. Manual copies wouldn't help. Also doing such copies is not a "docker approach", you can commit and push to registry container and work with it's internals later.

"Custom workspace" is used for building, it wouldn't change Node on what it was built.

`FYI, I need to access workspace in order to display reports like coverage, unit test reports, codestyle etc.` 
Unit/coverage plugins copy/transform/save any data they need and then visualise on build/project page. Doing manual changes in JENKINS_HOME may lead to broken jenkins, because it internal jenkins data.
