### ISSUE TITLE
Connection timeout weirdness 

### ISSUE THREAD

**Issue by jwhitcraft** [jenkinsci/docker-plugin#350]
When trying to spin up an instance, it says it can't connect to my cloud host, but when i press the test connection button in the docker cloud, it connects just fine and shows me the correct version of docker, 1.8.2, i'm using v0.15 and v0.14 of the plugin

I'm also jumping subnets, the 10.27.45 is out in AWS land where as my jenkins master is on my local machine.

Here is the log.

```
Asked to provision 1 slave(s) for: my-docker-cloud-10.27
Nov 09, 2015 9:20:15 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'registry.mycompany.net/my-jenkins-image:latest', for label: 'my-docker-cloud-10.27', in cloud: 'docker-cloud-10.27'
Nov 09, 2015 9:20:16 PM WARNING com.nirima.jenkins.plugins.docker.DockerCloud provision
Bad template 'registry.mycompany.net/refinery-git:latest' in cloud 'my-docker-cloud-10.27': 'shaded.org.apache.http.conn.ConnectTimeoutException: Connect to 10.27.45.26:4243 [/10.27.45.26] failed: connect timed out'. Trying next template...
```

**Comment by pfalcon** [comment]
We experience this after upgrade from 0.12.1 to 0.15 (yep, we didn't upgrade for a while because the plugin is broken since 0.12.1 - if not one thing, then another).

Example of our log is:

~~~~
INFO: Will provision 'linaro/jessie-arm64', for label: 'docker-jessie-arm64', in cloud: 'aarch64-04' Nov 09, 2015 10:13:17 PM com.nirima.jenkins.plugins.docker.DockerCloud provision WARNING: Bad template 'linaro/jessie-arm64' in cloud 'aarch64-04': 'shaded.org.apache.http.conn.ConnectTimeoutException: Connect to 10.10.0.219:2375 [/10.10.0.219] failed: connect timed out'. Trying next template...
~~~~

It's not that a press "Test Connection", I directly telnet to 10.10.0.219, port 2375 and have HTTP speaking to me. So, "connect timed out" error is completely nonsensical, what can be wrong there is that plugin does something weird. And it's not possible to diagnose it, because the real exception is swallowed, and instead out-of-context message is printed: https://github.com/jenkinsci/docker-plugin/blob/master/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L227

Please don't do that - ever. Especially in poor-quality code, for which jenkins plugins are infamous.

**Comment by pfalcon** [comment]
Update: I deployed current master with a simple patch https://github.com/jenkinsci/docker-plugin/pull/352 on another, less busy jenkins server. No problems seen there so far - it spawns docker slaves cheerfully.

**Comment by KostyaSha** [comment]
> We experience this after upgrade from 0.12.1 to 0.15 (yep, we didn't upgrade for a while because the plugin is broken since 0.12.1 - if not one thing, then another).

Have you reported your issues?

> Update: I deployed current master with a simple patch #352 on another, less busy jenkins server. No problems seen there so far - it spawns docker slaves cheerfully.

What was the reason of connection error?

**Comment by pfalcon** [comment]
> Have you reported your issues?

I didn't - I don't work on all Jenkins issues, I just heard folks not upgrading it because something didn't go well. I'm kinda 2nd level of support, getting involved when it doesn't work for a long, then ready to poke into source, etc.

> What was the reason of connection error?

Ok, if the above wasn't clear enough, here's complete timeline:

1. Server A was updated from docker plugin 0.12.1 to 0.15, leading to not docker builders being launched, with entries in jenkins log like in https://github.com/jenkinsci/docker-plugin/issues/350#issuecomment-155816836
2. Server A was downgraded back to 0.12.1.
3. I built https://github.com/jenkinsci/docker-plugin/commit/817f17ad428cc1db92549d1355dde6ea425692a3 with https://github.com/jenkinsci/docker-plugin/pull/352
4. As Server A was too busy, I installed my build on Server B. Everything went well - docker slaves were spawned, there were no "connect timed out" errors like above.
5. NEW: Today I finally installed it on Server A, where the original issue occurred. But it no longer occurred, slaves were launched w/o issue.

Conclusions: this issue was apparently fixed by commits since 0.15. So, I hope 0.16 will be released soon. Thanks!

**Comment by KostyaSha** [comment]
I found, `addProvisionedSlave` ideally shouldn't fail, it stores only counters. But counter is based on template and remove connection, so if bad template or broken connection was specified, then error may appear. Printing stacktrace here is valid.

> something didn't go well.

Without reports it will be impossible improve it or create test cases, from some user reported issues i created issue i created exact test cases.

**Comment by dnwe** [comment]
Isn't this just a duplicate if #347 and will be fixed when 0.16 ships ?

**Comment by pfalcon** [comment]
This leads to question: @magnayn , @KostyaSha : Any chance for 0.16 release soon? We're running on d564bca8acfdfcfc9d8f8a7c18bf5eeab52b5ea8 since the previous posts on this tickets, and I didn't hear any more docker complaints from our build engineers. So it would be just nice to run an official version.

**Comment by KostyaSha** [comment]
@pfalcon  https://github.com/jenkinsci/docker-plugin/issues/235#issuecomment-147975445

**Comment by pfalcon** [comment]
:-(

**Comment by magnayn** [comment]
Deployed. It'll likely take a while to propagate to the update centre.
