### ISSUE TITLE
How to use a container to pull private repo (which requires SSH key authentication)?

### ISSUE THREAD

**Issue by farahfa** [jenkinsci/docker-plugin#351]
Hello,

I've created a new image based on "evarga/jenkins-slave" image and I've generated an ssh key. However when I run a jenkins job that requires to use that SSH key authentication, the container doesn't use the SSH key that is there. However if I manually go into the container and pull that repo it works just fine.

I've been searching for a solution and found a couple:

http://stackoverflow.com/questions/18136389/using-ssh-keys-inside-docker-container
https://github.com/docker/docker/issues/6396
http://slash-dev-blog.me/docker-git.html

However, I'm not sure how this can be implied from the plugin itself. I'm sure the solution is easy, and this is definitely caused by the fact that I'm still new at this, so any help is greatly appreciated!

Thanks,

**Comment by KostyaSha** [comment]
According to jenkins best-practise usage you shouldn't put any ssh keys into environment manually. If you are using Git you should specify credentials for it. See https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin "SSH Keys".

**Comment by farahfa** [comment]
Hello I SSHed to Jenkins Master and I did a sudo su - jenkins.. Then I generated a key which resulted in creating SSH keys in /var/lib/jenkins/.ssh/ and I tried it again, and I still got Host key verification failed.

**Comment by KostyaSha** [comment]
@farahfa sorry, i didn't think that this doc is outdated. @MarkEWaite "SSH Keys" section seems wrong, should i update it and stop suggesting environmental keys?

@farahfa please ignore this text. Git plugin is already supporting ssh-credentials that allows you enter ssh key pair into Jenkins Credentials https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin and specify it for Git SCM job configuration. When job will do this scm checkout it will automatically place ssh key into target env. Docker is dynamic slave that shouldn't have built-in creds. 
Or maybe i missed something...

**Comment by farahfa** [comment]
So, basically I have a job that uses a docker image that contains node.js, npm, grunt, bower, which pulls files from our in-house gitlab repo. And while it's building it executes "grunt build" which from there it starts pulling for different repos. And it's failing on one of the repos (a private github repo) because of SSH authentication. I think the only reason is because it just doesn't know what key to use when jenkins starts building? I even used the same key that is used when pulling from our in-house gitlab repo which also didn't work.

**Comment by farahfa** [comment]
So my problem is after the SCM checkout. It happens during the "build"

**Comment by KostyaSha** [comment]
You didn't clarify that it grunt. You have different ways:
1) generate ssh key pair in docker image for jenkins user that will be used for running jenkins slave in docker slave. Then enable access for this key in github.
2) grunt build may utilise anonymous clones, then you don't need any keys
3) Ideal (untested) way is inject ssh key pair from credentials into some place https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Binding+Plugin that will be used by grunt/ssh and allow operate grunt

**Comment by farahfa** [comment]
Hmm, I was trying to do option #1. (I've already added a key in the slave image) but the problem is that it's not picking up that key. (Is there a way to tell it to use that particular key in the slave image?).

#2, Unfortunately I don't have much control of the private github repo to allow this option to work.

#3, I added a the private SSH key content into a "secret text" and I did a bind to the build environment with that, but I'm not sure what to do next with it. I tried creating a shell script that does the following

mkdir .ssh
echo $GITHUB_SSH_KEY > id_rsa
chmod 600 .ssh/id_rsa

then tried ssh -T git@github.com which also resulted in "Host key verification failed". I know I probably messed that up a lot, but I am truly clueless at this point. :/

**Comment by KostyaSha** [comment]
I can suggest ask this question on jenkins user list. I see nothing specific to this plugin.

**Comment by bernardgut** [comment]
Hi

I am hitting the very same issue and it is very problematic as the current "fix" is this : http://stackoverflow.com/questions/15174194/jenkins-host-key-verification-failed 

which I cant do every time I fire a dinamic slave. I have been trying to make this work for a while now and think this is very anoying as it renders the whole docker slave container pretty much useless. 

So the question remains: 
I have a private github repo set up with the public key. I have Jenkins set up with the docker plugin. I have the private key in the creds plugin. What are the next steps to spawn a docker container that can actually pull from a private github repository without giving a "Host verification failed" error ??

mystery mystery...

**Comment by MarkEWaite** [comment]
Since the slave is a docker container, could you avoid the problem by
adding a .ssh/known_hosts file to the docker image for the slave user so
that the host key is known?

Mark Waite

**Comment by bernardgut** [comment]
Hi Mark, thanks for the quick answer.

So I spent last night into digging a bit on how jenkins manages ssh creds and how to integrate that with docker slave builders and I realised that I was doing a compbination of things wrong. Because of the way information is disseminated all over the place, I am sure I am not the only one who will have this issue here is my *jenkins definitive guide to build within docker containers, with private git repos*:

*NOTE: This allows you to build only when the docker deamon runs on the same machine as the jenkins instance. I have not tried to build remotely on containers. If anyone has any "definitve guide on how to remotely launch jenkins slave docker containers with docker-plugin", please post it below.*

1. Install Jenkins *on bare metal*. You can use the official "jenkins docker container" to spawn a jenkins instance **but be aware that :** (1) you will have trouble with accessing the docker socket on the host from the jenkins container (see [this](http://container-solutions.com/running-docker-in-jenkins-in-docker/) especially the comment section), and (2) you need to spend some time to make the jenkins container drop to a shell that you can use to configure the ssh step below. ***Because of the above I strongly advise against using the "Jenkins docker image" for now with the docker-plugin.***
2. plugins : 
    - github (or git if you host your own bares)
    - workspace cleanup
    - multiple SCM (in my case I had multiple private repos)
    - docker-build
3. Configure jenkins to work with ssh keys and add keys in the ~/ssh folder. NOTE that the jenkins cred plugins work requires that **you do not copy keys from another user in the jenkins $HOME directory** (I wasted quite some time figuring this one as everything works when you git clone from the jenkins user to test, but then it doesnt work in your docker-plugin slaves giving you the "host verification failed" error even if you added your git provider to `known-hosts` and ran the ssh-agent):
    - log into jenkins@yourhost
    - ssh-keygen -t rsa (do not copy keys around from another user)
    - now add key to your git server authorized keys (or in my case in your github account "ssh keys" parameters)
    - add the key to the local ssh-agent `eval \`ssh-agent -s\`` then `ssh-add`
    - log out and restart jenkins: `sudo service jenkins restart`

4. finally, in your jenkins project config, configure the git repos to use the jenkins user ssh key that you configured when cloning:
   - go to project->configure->source code mgmt, add any/all your repos with the form `git@github.com:user/project.git`
   - add credentials so that jenkins can access your private repos : "credentials -> add" :
      - "SSH Username with private key"
      - "Username" : "jenkins"
      - "Private key From a file on Jenkins master" : "~/.ssh/id_rsa" (the other options didnt work for me.) 
      - "Passphrase"/"description" : leave empty
5. Thats it for the jenkins master configuration. Now you need to configure your docker deamon so that jenkins can connect and fire containers : 
   - In `/etc/default/docker` add `DOCKER_OPTS="-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock"`. This allows docker deamon to speach with other processes on the same machine (e.g. the jenkins instance). I have not tried to build on remote containers (assuming that's even supported). 
   - create a "jenkins-slave" image within which you will run your builds. Add anything you need to build in there here is the one I inherit from to create my build environments : 
     ```
     FROM ubuntu
     MAINTAINER <yourname> <youremail>

     # Install dev requirements
     # NOTE : Keep the following list in alphanumerical order.
     RUN apt-get update && apt-get install -y \
         openssh-server \
         openjdk-7-jdk
     RUN sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd

     RUN mkdir /var/run/sshd
     RUN adduser --quiet jenkins
     RUN echo "jenkins:jenkins" | chpasswd
     EXPOSE 22

     USER jenkins
     #Make ssh dir
     RUN mkdir /home/jenkins/.ssh

     # DO NOT EVER DO THE FOLLOWING THINGS (SECURITY) : 
     #COPY jenkins_rsa /home/jenkins/.ssh/id_rsa
     #COPY jenkins_rsa.pub /home/jenkins/.ssh/id_rsa.pub
     #USER root
     #RUN chown jenkins:jenkins /home/jenkins/.ssh/id_rsa
     #RUN chown jenkins:jenkins /home/jenkins/.ssh/id_rsa.pub
     #USER jenkins
     #RUN chmod 600 /home/jenkins/.ssh/id_rsa
     #RUN chmod 600 /home/jenkins/.ssh/id_rsa.pub
     #USER jenkins
     #RUN /bin/bash -c "eval '$(ssh-agent -s)'; ssh-add /home/jenkins/.ssh/id_rsa"

     # Create known_hosts
     RUN touch /home/jenkins/.ssh/known_hosts
     # Add github (or your git server) fingerprint to known hosts
     RUN ssh-keyscan -t rsa github.com >> /home/jenkins/.ssh/known_hosts

     USER root
     CMD ["/usr/sbin/sshd", "-D"]
     ```

    - build it and add it to your docker-plugin settings (follow the official "configuration" instructions [here](https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin). Remember to modify the last part where you add the server fingerprint to known_hosts with your own git provider

Any variation of the above steps resulted in the bui;d container not beeing able to pull private repos, or worst: in one case it was stuck in a container boot loop (it fired a container every 10 secs, said it was "offline" then fired another without cleanup).

good luck 
- Bernard

**Comment by farahfa** [comment]
Thanks Bernard! I gave up a long time ago on this issue and had to work around it.. This sure will help in the future though!

**Comment by fmoezinia** [comment]
Really Easy Fix:

Use Personal Access Tokens (generate one in settings on Github)
Then just RUN    git clone https://MY_TOKEN@github.com/user-or-org/repo
in your dockerfile

**Comment by ndeloof** [comment]
0.17 do rely on docker-commons and as such support various docker authentication credentials

**Comment by cwyark** [comment]
Follow up this discussion. docker support a enhanced build by passing ssh connection to your dockerfile. https://docs.docker.com/develop/develop-images/build_enhancements/
