### ISSUE TITLE
Containers being shutdown before jobs start under heavy build queue load

### ISSUE THREAD

**Issue by maxfields2000** [jenkinsci/docker-plugin#354]
We're still debugging, but to help you understand the situation. We have multiple jobs that use the same docker image as their build environment. When we end up with 3 or more jobs in the queue, especially over 6, that all use the same image, things start to break down quickly.

Visibly what happens is that the Docker Plugin is creating dozens, sometimes hundreds, of containers and then before the job actually starts running, the build node is disconnected.  You can watch Jenkins spin trying to create nodes, watching 3 or 4 containers spin up, but no jobs start because the node immediately goes into a suspended/shut down state.

When tracing logs and source code, what appears to be happening is that with an "idleTimeout" of "0" (the default setting), the Jclouds plugin is running the 'check' code, deciding that the node has been "idle" and shutting it down, before the build queue even bothers to move the job into a running state.

I'm testing if an idleTimeout of "1" solves the problem (source code reading shows that's in minutes, would be handy if the UI mentioned it was a minute setting).  The issue there is then the node stays running for a bit over a minute after the job finishes and could get picked up again.

I'm not sure what the right way to approach this is. It appears that the decision to spin down a build node is not related to whether or not the job it was allocated for ran successfully.  One way might be to have one defined image per build job, but this also doesn't work well because then we'd have hundreds of images created (we run over 800+ build jobs in docker containers).

Looking for some guidance on how to deal with this issue.  In a perfect world a build in the build queue would only run on the container that was allocated for it, but the system doesn't garauntee that as it uses "labels" to tie jobs to build slaves the jenkins way.

**Comment by KostyaSha** [comment]
@maxfields2000 default idle timeout is 10

**Comment by KostyaSha** [comment]
@maxfields2000 say it to @jglick here https://github.com/jenkinsci/durable-task-plugin/pull/6#discussion_r43591170

**Comment by maxfields2000** [comment]
Ah, I see that you are correct. We haven't changed our configurations over multiple versions and our idleTimeout is set to 0 on all existing configs, but if I make a brand new one I see that it is 10.

 Is 10 something you recommend? I experimented with 1 minute all evening and it seriously stablelized everything nicely. So much so that I really think it shouldn't allow you to set it to 0 :)

We'll update our stuff accordingly, as well as our automatic testing/config suite so it sets a more reasonable idleTimeout as it definitely seems to be the trick.

**Comment by KostyaSha** [comment]
@maxfields2000 frankly speaking i thought that i wrote automatic update from 0 to 10 value, data migration in jenkins very tricky. 0 or 1 minute maybe not enough because of locks and periodic retention strategy checks (they are done every minute) so to exclude this race of condition i suggested 10 minutes. Normally this timeout shouldn't be used at all because job normally is killed as soon as build ends on it. 
In reality this value may be useful only for bad provisioning cases when something failed and jenkins wants spin-up all capacity or if slave was spined but didn't utilised i.e. queue item aborted after job provisioning. If you see the case when docker plugin runs many slaves, then it can be separate issue https://github.com/jenkinsci/docker-plugin/issues/337

@jglick thinks that `0` is good value and i used it in initial implementation. After debugging i found that jenkins core Cloud API do retention checks asynchronously and retention check is not aligned so it may end with slave deletion just after it was spined and before job get to executor.

@stephenc seems it impossible to have event driven slave deletion for queue cancellation until slave wouldn't know for what item it was requested to provision slave. I.e. item in queue, NodeProvisioner asks provision for Queue.Item instead of label or load, Cloud checks provisioning criteria and saves reference to item for run slave.

**Comment by stephenc** [comment]
@KostyaSha well it wouldn't be exactly that simple.

For starters, it would have to be something like `Map<PlannedNode,List<Queue.Item> provision(Label label, List<Queue.Item> items)` so that the cloud could indicate that it is returning node A for items X and Y and node B for item Z only...

Then of course things get more complex with e.g. workflow, where you may have multiple stages running on the same node... so we need to differentiate between

```
stage `first`;
node('a node') {
  ...
}
stage `second`;
node('a node') {
  ...
}
```

Where it is acceptable to provision two distinct nodes

Whereas

```
node('a node') {
  stage 'first';
  ...
  stage 'second;
  ...
}
```

Both of the two sub-tasks need to run on the same node with the workspace persisted.

The Queue is going to see two separate "Task"s with stopping and starting in between and it is a mistake for docker to deprovision and reprovision across those two tasks (not that I'm singling docker out here... oc-cloud has the same problem)...

You can also have the same effect without invoking the spectre of s/workflow/pipeline/g; as the job API lets you have multiple tasks in the same job where the single-shot retention strategies are insufficient... the only difference with workflow is that these other job types can typically know up front that they will need to run N sub-tasks and can therefore "pin" their execution with a carefully placed flyweight task for example. With workflow, as the actual workflow script can come from SCM and the script logic can have the behaviour change in reaction to the actual build events.

I guess where I am coming from is that the Queue and provisioning APIs need a significant rework in light of the change in primary assumptions that more advanced job types realize for Jenkins.

/me heads off to petition day job's Product Management for time to work on this

**Comment by stephenc** [comment]
Did I mention resuming workflow stages... that sounds like a whole lot of fun with 

```
node('docker') {
  stage 'first';
  ...
  stage 'second';
  ...
}
```

Though I suspect in such cases you are actually supposed to be using different primitives that are docker specific... (smells like a hack to me though)

**Comment by KostyaSha** [comment]
@stephenc i thought about resuming with some container commit/start logic, Cloud should provide some `Resumable` interface then.
But of course multiple executors will be under question...

**Comment by ndeloof** [comment]
AFAICT this issue related to the "Cloud Retention Strategy" based on a timeout to stop containers. The "Once Retention Strategy" has been introduced in the meantime and better address this scenario, i.e. will stop container on build completion, and also offers a timeout in case the build completion was not detected (sic). Base on this, I'm closing this issue
