### ISSUE TITLE
[improvement] Make option to not export cloud DOCKER_HOST to slave

### ISSUE THREAD

**Issue by DusteDdk** [jenkinsci/docker-plugin#394]
My setup:

Host: Ubuntu running docker daemon, TCP bound to IP of docker0 NIC.
Jenkins master image: Container running in docker daemon on Host.
Docker-plugin configured to use Host docker damon for provisioning slaves.
Jenkins slave image: Provisioned by docker-plugin, an environment to build software, which also has docker installed, for executing build step "create docker image of the software that was just built".

Issue:
I'm starting a docker daemon inside the slave, I wish the docker client inside the slave to use that daemon, but docker-plugin on the Jenkins Master seems to have exported DOCKER_HOST to the Slave environment, making the docker client inside the slave use the docker daemon from the Host, instead of the locally running one.

Workaround (needs to be done in all jobs that need to execute docker):
In the build script (which runs witin the slave container): unset DOCKER_HOST before executing any docker commands (such as building an image)

Pretty Solution:
Under "Cloud > Docker > Container > Advanced"  configuration on the master, make a (default true?) boolean option with a name similar to "export DOCKER_HOST variable to container environment".
Suggested description: "When calling the docker client within the container, exporting DOCKER_HOST variable causes that docker client to use the same docker daemon which runs the slave container. Disable this if isolation is desired and another docker daemon is to be run inside this container."

Potential issue:
I don't know how this plugin is implemented, one could imagine that a (less ideal) implementation where the variable is exported so that the docker plugin can execute a docker client can be inside the slave container in order to, for example, commit that container, but I would expect such commands to be run inside the jenkins master, not on slave itself (since the master already needs to execute a docker image to provision slaves, I do not see a technical argument for why that should be the case).

**Comment by KostyaSha** [comment]
Everything more cool. Vars allows you mounting side containers and easily running commands using the same workspace in other containers. That was simple "shellflow" that had no any DSL or java abstractions on top of it. I can document this if you want. 

But you are right of course that may be unexpected sometimes ;)

**Comment by DusteDdk** [comment]
Hi, thank you for your reply. I do think documenting it would be nice, I guess not that many people are running docker inside docker, so it's likely not something a lot of people are seeing.

**Comment by cjthorne** [comment]
Just to add my vote for a change here. We use docker in docker builds for almost all our builds and therefore have many existing jobs run by many teams. We have not upgraded from docker plugin 0.13 for this reason for several months.

Having the option to not set the DOCKER_HOST variable in the job or, even better, globally would make upgrade possible earlier.

I think the use of the docker daemon on the host is not suitable for docker builds in general because
- the docker daemon on the host it can be at a different version to the docker containers running the builds. This may be for testing reasons, or to take advantage of new features while making sure the docker versions work on older builds. 
- upgrading the docker daemon on the host will mean, in some cases, the slave images using docker will fail without upgrading the docker client. Similarly, if you update the slave image version of docker you have to upgrade the docker daemon on all Jenkins slaves first.
- if you are building images in the jenkins job, the image cache on the host machine will have images from other builds which can lead to non-deterministic builds.
- the image cache on the host machine will gradually fill up needed constant maintenance. Using docker in docker means that the images will be removed at the end of every job.

**Comment by KostyaSha** [comment]
> if you are building images in the jenkins job, the image cache on the host machine will have images from other builds which can lead to non-deterministic builds.

Only if you provided credentials and allowed this job to connect to daemon host. The question is what limits job to do the same without variables? That the question for security and trusteeship in your infra.

> the image cache on the host machine will gradually fill up needed constant maintenance. Using docker in docker means that the images will be removed at the end of every job.

True, but this will also mean that there is no caches and it will cause delays. You can try spotify/docker-gc . In any case host usually will be filled with images and for better infra usage you would need docker-gc tool.

Yes, of course injection could be done optional, but jenkins doesn't provide any UIs or options for EnvironmentContributors. What i really don't understand why you can't redefine or unset this variables?

**Comment by jswager** [comment]
Hello, I see a PR that seems to address this issue - https://github.com/jenkinsci/docker-plugin/pull/450

We have a problem where for the temporarily created slaves, we want to specify a different DOCKER_HOST.  We provide creds to it via the Jenkins job, so authentication is not a problem.  We've tried to override DOCKER_HOST via the image variable setup, but it gets overridden by the plugin.

**Comment by eaglerainbow** [comment]
Apparently d7fe499457ebd36c97cf79dabec9e2c0b8f22ab8 / #450 should solve this issue. NB: Coding of #450 is merged to "master", but no new version got released so far.

**Comment by ndeloof** [comment]
released in 0.17
