### ISSUE TITLE
Total container cap of 0 reached, not provisioning

### ISSUE THREAD

**Issue by kristoflemmens** [jenkinsci/docker-plugin#44]
Setting for container cap says 0 (unlimited) but the plugin won't provision. When I set the container cap to 5 or something else the plugin starts with provisioning.

![docker_screenshot](https://cloud.githubusercontent.com/assets/1329803/3384489/54c4153a-fc5b-11e3-8bd6-90910fa678fe.png)

**Comment by jonathanperret** [comment]
Just hit upon this as well. What the documentation at https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin says:

> Container Cap: The maximum number of containers that this provider is allowed to have running, defaults to blank which disables the limit

used to be true, but changed in https://github.com/jenkinsci/docker-plugin/commit/bde53df15d84e746dba3a40fcaa050bf60260ab1 (by @KostyaSha) so that a blank entry is understood as zero, and sets the limit to zero.

It's not clear whether the loss of that functionality was deliberate, so I suggest reopening this issue until someone with a broader view can decide whether to fix the documentation or the code.
