### ISSUE TITLE
Variables expansion in "Docker xxx" build step

### ISSUE THREAD

**Issue by yermulnik** [jenkinsci/docker-plugin#466]
I'm trying to set up Jenkins job to build/push images for different projects. So I created the Job which is downstream for several projects. Upstream jobs pass path to Dockerfile, repository name and image tag via Parameterized Build/Trigger Plugins. But Docker Plugin fails to expand those vars and to find Dockerfile respectively:
```
[...]
Docker Build
Docker Build: building image at path /${WORKSPACE}/${DOCKERFILE_DIRECTORY}
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Dockerfile does not exist
[...]
```
Is there a way to use Env vars with this Plugin? Or can you add this possibility, pls?

ps: Jenkins is v2.19.3, Docker Plugin is v0.16.2

**Comment by ThStock** [comment]
+1
I tried to build an docker image like this:
```mycompany/app:${GIT_TAG}``` that should be replaced with e.g. ```mycompany/app:1.3.4```

btw: GIT_TAG variable is created with https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin

**Comment by newsworthy39** [comment]
+1 
I tried to build an docker image, like this company/app:${BUILD_TAG} and it got reported as "{BUILD_TAG} in plugin-version 1.0.1. Building it like ':somestuff', tags it corrently. It seems the variables does not get expanded:

Tagging built image with company/app:${BUILD_TAG}
ERROR: Build step failed with exception
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"invalid tag format"}
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:109)

**Comment by soster** [comment]
+1
Would be super useful

**Comment by parin921996** [comment]
+1
Definitely needed feature..

**Comment by michellehalliwell** [comment]
+1
When tagging an image, using an environment variable was previously working using version 0.16.2 of the Docker Plugin.  After updating the plugin to version 1.0.4, I'm now seeing this issue again where the environment variable is read at face value rather than evaluated.

`ERROR: Build step failed with exception
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"invalid reference format"}
`

**Comment by terminalv1** [comment]
+1
would make the continuous delivery so much more convenient

**Comment by aleksandarknezevic** [comment]
Seems like it is solved in Docker plugin version 1.1! Now It is possible to push imagename:${BUILD_NUMBER} \o/.

**Comment by anneq** [comment]
Been bitten by this too. No easy way to revert to the 0.16.1 version. Yikes, what a mess.

**Comment by stmlange** [comment]
Leaving this here for the next person to bump into the issue (`InternalServerErrorException: {"message":"invalid tag format"}`) was caused on my side because I accidentally left the configuration empty leading to the following xml:
```
    <com.nirima.jenkins.plugins.docker.DockerJobProperty plugin="docker-plugin@1.2.1">
      <additionalTag></additionalTag>
      <pushOnSuccess>false</pushOnSuccess>
      <cleanImages>true</cleanImages>
    </com.nirima.jenkins.plugins.docker.DockerJobProperty>
```
unfortunately the error message is still cryptic and caused a long chase of the root cause :/
