### ISSUE TITLE
help pipeline script syntax 

### ISSUE THREAD

**Issue by jhsea3do** [jenkinsci/docker-plugin#672]
I have two docker server node1 and node2,  i want create a global container agent cross any stage in one pipeline, i must define the agent at first.

I've created a cloud name 'node1' via docker-plugin, please see my screen shot attached.

Here  is my  job script,  i want change the label value  to run container agent in node2 or node1, 

```groovy
pipeline {
    agent {
      docker {
        image 'centos:centos7' 
        label 'node1'
      }
    }
    stages {
      stage('Prepare') {
        steps {
          sh """
          echo \$(hostname)
          """
        }
      }
      stage('Build') {
        steps {
          sh """
          echo \$(hostname)
          """
        }
      }
    }   
}
```

But my pipeline job always pending with the error message:

```
Jenkins doesn’t have label node1
```

So i have to modify the system environment variables under "Jenkins > configuration > Global properties ",  and copy {cert,key,ca}.perm in to ${HOME}/.docker directory of my jenkins server .

```
DOCKER_HOST=tcp://10.139.1.1:2376
DOCKER_TLS_VERIFY=1
```
and remove " label 'node1' "  from my pipeline script,  then the job works.  but when i need use node2 as docker server, i need change the settings to "DOCKER_HOST=tcp://10.139.1.2:2376", this is a global setting.
 

 - [1.1.4 ] docker-plugin version you use
 - [2.121.2 ] jenkins version you use
 - [18.03.0-ce ] docker engine version you use
 - [ ] details of the docker container(s) involved and details of how the docker-plugin is connecting to them
 - [ ] stack trace / logs / any technical details that could help diagnose this issue

![image](https://user-images.githubusercontent.com/91740/43242541-363d784c-90d4-11e8-9dfb-54fbab11f23d.png)

**Comment by jhsea3do** [comment]
I need an easy method to switch docker server between the node1 and node2,  can i ?

**Comment by jhsea3do** [comment]
the 'docker' keyword only accept these parameters:

[image, alwaysPull, args, containerPerStageRoot, customWorkspace, label, registryCredentialsId, registryUrl, reuseNode]

**Comment by pjdarton** [comment]
This is not a support facility.  This is for bug reports, not requests for help.  For help, go to the Jenkins usergroups.

Using the pipeline syntax you described (which is documented [here](https://jenkins.io/doc/book/pipeline/docker/)), your pipeline is using the `docker-workflow` plugin and not the `docker-plugin` plugin (this is the github area for the `docker-plugin`).
You're having trouble because you're partly-configuring the `docker-plugin` plugin, then using the other in your pipeline.

FYI you're not the first person to confuse the two, e.g. #671 - the conversation in there might be useful to you.
