### ISSUE TITLE
dockerNode stops after ~10 minutes

### ISSUE THREAD

**Issue by Typz** [jenkinsci/docker-plugin#687]
I am trying to use dockerNode() to perform builds using a specific version of the docker image on a swarm cluster.

This approach makes it much simpler than creating a template each time (since we use a different tag each time), or having a generic template which allows to issue docker commands to run another container.

However, the container stops after ~10 minutes, leaving the build stuck in that state (with no option but to abort it manually). The build log looks like this:
```
10:14:19 Cannot contact docker-007258gpv262a: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on docker-007258gpv262a failed. The channel is closing down or has closed down
Aborted by Francois Ferrand
10:50:39 Could not connect to docker-007258gpv262a to send interrupt signal to process
```

It looks like there is a timeout (possibly the default idle timeout set for the retention strategy?), even though the build is otherwise proceeding normally until then.

It maybe worth noting however that even though the build is indeed executed on that node, it is not listed in the node's executors : in Jenkins UI, the build can only be seen through the job' page. Not sure if this is related, but it may also impact the detection of idle-ness (and in any case is a disturbing UI experience).

If you get some troubles with docker-plugin, please report
 - docker-plugin version: 1.1.5
 - jenkins version you use: 2.121.3
 - docker engine version you use: swarm/1.2.8 running on 17.09.0-ce

**Comment by molecul** [comment]
have a same problem

**Comment by pjdarton** [comment]
Hmm... thing is, this plugin creates a docker container, tells the Jenkins core about it, and then leaves it alone until the Jenkins core disposes of it (usually by the Jenkins core invoking the retention strategy's disposal logic).
Maybe I'm missing something here, but while I accept that you're using this plugin and seeing this problem, I don't see how it could be a bug in this plugin; if the Jenkins core's activity isn't showing up in the right places in the Jenkins core's UI, then that's likely a bug in the Jenkins core, and the use of this plugin to demonstrate that bug is incidental.

Feel free to prove me wrong by providing a full repro case (and re-open the issue), but I don't _think_ it's an issue with this plugin.
