### ISSUE TITLE
parameter Idle timeout  not work, slave after finishing a job will be always killed

### ISSUE THREAD

**Issue by effectivecui** [jenkinsci/docker-plugin#689]
- [ 1.1.5] docker-plugin version
 - [2.143 ] jenkins version
 - [ 18.06.1-ce, build e68fc7a] docker engine version 

Just as title, regard as what is the idle timeout, slave can not alive

**Comment by pjdarton** [comment]
Yup; working as designed - once a slave has finished a build, it's destroyed (because docker slaves have a single-use retention strategy).
The "idle timeout" isn't what you're assuming it is.  The "idle timeout" is the length of time a container will be kept alive _unused_ before it gets quietly disposed of - that's used when containers are started (due to a demand for slaves) but which don't get used (e.g. builds have run elsewhere or were cancelled).
