### ISSUE TITLE
 cannot use jenkins paramter in volumes

### ISSUE THREAD

**Issue by osamaahf** [jenkinsci/docker-plugin#695]
Hello, 

I am trying to specify paramter in volumes but it seem not working, 
Docker-plugin didn't get the value of paramter instead of that he create a new folder in the workspace.

<img width="558" alt="deploy app" src="https://user-images.githubusercontent.com/44613853/47730263-19a5c480-dc62-11e8-91b2-dfd421d36107.PNG">

In the server i see a new folder ${ProjectName} instead of replace the value of that parameter, so I have that:

`ls /var/jenkins_home/workspace/deploy-app/git-repo ` 

 ` my-project  ${ProjectName}
 ` 

 - [ ] docker-plugin version : 1.1.5
 - [ ] jenkins version : 2.148
 - [ ] docker engine version : 17.03.3-ce

docker plugin is connected with tcp 

Any idea please ?

Thank you

**Comment by pjdarton** [comment]
This is working as intended - the code responsible for telling docker what volumes(s) to mount (DockerTemplateBase.java's [`fillContainerConfig`](https://github.com/jenkinsci/docker-plugin/blob/3c26f25d264f6da13a9823662f2237e25f721ba8/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java#L542) method) has no parameter substitution functionality, because there really isn't much useful substitution that can be done here.

If you were hoping that `${ProjectName}` would be evaluated to be the name of the Jenkins job that was running then you're out of luck - the code here has no idea (or control) over which Jenkins job will be run on this docker container, so it cannot do any project-specific variable substitution at this point.
FYI This code is invoked when Jenkins realizes that it doesn't have enough executors to run all the queued builds - it's called when the Jenkins core wants more executors, but it isn't told (by the core) what job will be running on the container (because the core hasn't decided that yet).  The only variable-substitution that this code could process here would be system-global environment variables, and that isn't going to help you in this case (and isn't going to help in many other situations either, which is why nobody wrote the code to make the plugin do that, although there's no reason it couldn't).

 - If you want a Jenkins job to run on a container that's started with job-specific parameters then you need to define a Jenkins _pipeline_ that specifies what container you want that job to run on and how that container should be configured _for that build_.
