### ISSUE TITLE
Node Environment Variables Case-Insensitive

### ISSUE THREAD

**Issue by zlacelle** [jenkinsci/docker-plugin#699]
docker-plugin: `1.1.5`
jenkins: `jenkinsci/blueocean:latest`
docker-ce: `5:18.09.0~3-0~ubuntu-bionic`

When setting the "Node Properties" -> "Environment Variables" section of the Docker Agent Templates, you cannot set two environment variables which are case-insensitive identical. For example:

http_proxy
HTTP_PROXY

However, Linux docker containers are case-sensitive and different services use different case conventions.

**Comment by elenoir** [comment]
This is related to https://issues.jenkins-ci.org/browse/JENKINS-16255
For the moment the plugin leverages the Jenkins NodeProperty object.

**Comment by pjdarton** [comment]
Yup, Jenkins generally tries to be platform agnostic, not all platforms (e.g. Windows) support environment variables who differ only in case, so Jenkins doesn't either and the way `NodeProperty` is coded reflects this.
...and given that Microsoft are making big efforts to do docker on Windows, it would probably be taking the plugin in the wrong direction to make the plugin do something that's different from the rest of Jenkins _and_ which wouldn't work on Windows.

In practice, if you avoid duplication, you'll find that Jenkins does at least _preserve_ the case of what you set (as long as it isn't colliding with another name) ... although I acknowledge that this won't help you much if you're dealing with a docker container that wants both `http_proxy` (the widely accepted env var name for controlling the http proxy settings) and `HTTP_PROXY` (probably only ever used by software written by programmers who are used to working with Windows/MSDOS) at the same time.

Overall, I think that this is a jenkins-core issue not a docker-plugin issue, and affecting all unix-based slave nodes not just docker containers.  I think that any solution to this issue would be best implemented as an enhancement to the Jenkins core code (which this plugin would then benefit from) rather than as code specific to this plugin.
