### ISSUE TITLE
'Jenkins' doesn’t have label 'XXXXXX' because of com.github.dockerjava.api.exception.NotFoundException

### ISSUE THREAD

**Issue by cpottiers** [jenkinsci/docker-plugin#704]
- docker-plugin version 1.1.5
 - jenkins version 2.144
 - docker engine version master : 17.05.0-ce / slave 18.06.1-ce & 17.05.0-ce (same bug)

Hi, i have configured a docker agent template which run a docker image in order to build our packages.  

- On the first build, jenkins pull & run the image, build our package and stop (on IO error) & delete the container.  
```
Dec 10, 2018 5:23:57 PM io.jenkins.docker.DockerTransientNode$1 println
INFO: Disconnected computer for node 'xxxxxxxxx-yyyyyyyyy'.
Dec 10, 2018 5:23:57 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
INFO: I/O error in channel xxxxxxxxx-yyyyyyyyy
java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:127)
        at io.jenkins.docker.client.DockerMultiplexedInputStream.readInternal(DockerMultiplexedInputStream.java:41)
        at io.jenkins.docker.client.DockerMultiplexedInputStream.read(DockerMultiplexedInputStream.java:25)
        at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:91)
        at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
        at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
        at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
        at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
```
- On the second build, jenkins try to start the previous container (which have been deleted) and throw a SEVERE exception : 
```
SEVERE: Error during callback
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such container: e85ad6e6f0adf8e97f4ce5af2df2d85183e7b4d3af5f0cf3b5ea7eafa9d867f9"}`
The build freeze on message `'Jenkins' doesn’t have label 'XXXXXX'
```

I can't see why jenkins try to reuse the previous container and why it can't try to run an other container...  

Note : I use "attach docker container" method with the custom image :  
```
FROM maven:3.5.4-jdk-8-alpine

ENV NODE_VERSION 8.9.4
ENV YARN_VERSION 1.3.2
ENV DOCKER_CLI_VERSION 17.03.0-ce

RUN apk add --no-cache \
        libstdc++ \
        binutils-gold \
        curl \
        g++ \
        gcc \
        libgcc \
        linux-headers \
        make \
        python \
        xz \
    && curl -fsSLO --compressed "http://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION.tar.xz" \
    && curl -fsSLO --compressed "http://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt" \
    && grep " node-v$NODE_VERSION.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
    && echo "tar -xf \"node-v$NODE_VERSION.tar.xz\"" \
    && tar -xf "node-v$NODE_VERSION.tar.xz" \
    && cd "node-v$NODE_VERSION" \
    && ./configure \
    && make -j$(getconf _NPROCESSORS_ONLN) \
    && make install \
    && cd .. \
    && rm -Rf "node-v$NODE_VERSION" \
    && rm "node-v$NODE_VERSION.tar.xz" SHASUMS256.txt

RUN apk add --no-cache curl gnupg tar \
  && curl -fsSLO --compressed "http://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
  && mkdir -p /opt \
  && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
  && ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
  && ln -s /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
  && rm yarn-v$YARN_VERSION.tar.gz

RUN apk add --no-cache curl \
    && mkdir -p /tmp/download \
    && curl -L "https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_CLI_VERSION.tgz" | tar -xz -C /tmp/download \
    && mv /tmp/download/docker/docker /usr/local/bin/ \
    && rm -rf /tmp/download \
    && apk del curl \
    && rm -rf /var/cache/apk/*

RUN apk add --no-cache git openssh
```

**Comment by cpottiers** [comment]
Hello, here's news about the problem.
I have build an other jenkins master which is configured to build on same slave with same docker image.
With this master I have no problem. All builds are succeed.

So I compared the logs from master 1 to master 2 :
- the error `java.net.SocketException: Socket closed` is present both (so this not help)
- the error `com.github.dockerjava.api.exception.NotFoundException` is not present in master 2
- another usefull logs in master 1 (can be the root cause) at the end of a succeed build and maybe provocating the freeze of the next build :
```
Dec 12, 2018 3:10:41 PM hudson.remoting.Request$2 run
WARNING: Failed to send back a reply to the request hudson.remoting.Request$2@4454b366
```

Any help appreciated

**Comment by pjdarton** [comment]
FYI the `dockerjava` library is known to log normal operational situations as exceptions, which confuses things a great deal.  In general, if you see an exception from `com.github.dockerjava` then you can ignore it _unless_ there's another exception logged at the same time from another source.  If you're seeing two exceptions (one from `dockerjava` and one from something else) then the dockerjava exception _might_ help with debugging the underlying cause of the other exception, but on their own they're meaningless and should be ignored.
e.g. it's perfectly normal to see `NotFoundException` being logged by `dockerjava` as it's possible for multiple threads in Jenkins to try to delete the same container at once (or for Jenkins to ask docker to ensure that a container doesn't exist when Jenkins deletes the docker slave node) - that'll result in a NotFoundException being returned to the Jenkins docker-plugin code which will then handle the exception or log it itself (in general, it's bad practice for code to log exceptions it is throwing as part of correct operation - it's best if code only logs exceptions that it doesn't handle).
The `Socket closed` is also expected when slaves are being closed down (if the slave container is being destroyed, it's expected that the connection to that slave will close); it's only an error if it happens unexpectedly, and even then that's usually a symptom of another issue rather than being the problem itself - best check the logs for anything else that happened (either on Jenkins or on the docker host itself) at that time.
