### ISSUE TITLE
Proper way to use the dir() function inside docker image

### ISSUE THREAD

**Issue by jungopro** [jenkinsci/docker-plugin#710]
Hello

I read through a few cases including [this](https://github.com/jenkinsci/docker-plugin/issues/561) and [this](https://github.com/jenkinsci/docker-workflow-plugin/pull/123) but I still couldn't resolve my issue

My environment is:

- Jenkins 2.107.1
- Docker plugin
- Using official docker ssh slave docker image
- Docker version on the VM that is used as "docker cloud" is: 18.06.1-ce

My case:
I'm trying to build & test a docker image using the docker ssh slave.
When the slave starts it has the docker cli installed and /var/run/docker.sock mounted from the vm to the slave

Jenkinsfile snipplet:

```jenkinsfile
stage('Build Docker Image') {
    docker.withRegistry("http://${docker_registry}",'cred-id-from-jenkins') {
        dockerImage = docker.build("myImage:${env.Build_ID}", "-f mydockerfile")
    }
}

stage('Test') {
    dockerImage.inside('-u root') {
        sh '''
            cd /service 
            npm run testx
        '''
        junit 'xunit.xml'
    }
}
```

replacing the test stage to doesn't work as well:
```jenkinsfile
stage('Test') {
    dockerImage.inside('-u root') {
        dir("/service") {
            npm run testx
            junit 'xunit.xml'
        }
    }
}
```

The problem is setting the workdir in the test stage, that will propagate to **both** the npm run testx step **and** the junit step
I need this since the docker image is running inside **/service** and the xunit.xml is created in that folder. 
junit rolls back to the original workdir and can't find the file (even if i replace with **junit '/service/xunit.xml'**

- I tried on both declarative and scripted pipeline with no luck
- I tried to pass the workdir as -w argument like _dockerImage.inside('-u root -w /service')_ but the pipeline overrides it with it's own workdir _(-w /home/jenkins/workspace...)_

What's the proper syntax to run the junit and pass it the file location?

Thanks
Omer

**Comment by pjdarton** [comment]
This area is for reporting bugs in the Jenkins plugin `docker plugin`.  You're asking a generic question about how to use Jenkins pipelines _and_ you're using the syntax for the Jenkins plugin `docker-workflow`, which isn't the same as this plugin (yes, there are two plugins; no, it isn't explained very well).
i.e. This isn't the right place for your query.

I don't know the answer to your question, but in my experience, the way Jenkins builds work when they're executing inside a docker container is exactly the same as when they're executing in any other kind of Jenkins slave node (because, once Jenkins is connected to the container's slave process, it works just like any other).
You should ask in the general Jenkins channels, e.g. http://webchat.freenode.net/?channels=jenkins or https://groups.google.com/forum/?nomobile=true#!forum/jenkinsci-users or, if folks there tell you that it's a `docker-workflow` issue then you need to go to https://github.com/jenkinsci/docker-workflow-plugin instead.

PS. I also would suggest that you'll probably have an easier time using the Jenkins junit functionality if you put your test result files within the build workspace where it expects to find them, otherwise you're trying to solve more than one problem at once.
