### ISSUE TITLE
Export image tag/id to build steps (or post) in Pipeline jobs

### ISSUE THREAD

**Issue by brianjmurrell** [jenkinsci/docker-plugin#715]
Similarly to [this question](https://groups.google.com/forum/#!searchin/jenkinsci-users/How$20to$20get$20the$20Docker$20image$20id$20used$20by$20a$20job%7Csort:date/jenkinsci-users/vl_2Zg6X_-I/Nz0G79UIBQAJ) (which really didn't get any good answers) , due to [Jenkins not doing it's own docker image garbage collection](https://issues.jenkins-ci.org/browse/JENKINS-40723) I would like to implement my own garbage collection based on which images are actually current and which are stale rather than the more naïve implementation in [docker-gc](https://raw.githubusercontent.com/spotify/docker-gc/master/docker-gc) of just removing the oldest images without regard to whether they are actually still currently being used by Pipeline jobs or not.

To do so, I need to keep an accounting of which images are being used by which jobs.  This would need to be done in the _step_, or _post_ of a Pipeline job and as such it would be useful if some kind of identifier of the image (image ID, tag, etc.) were exported to the job _step_ and/or _post_.

**Comment by pjdarton** [comment]
Firstly, if you're using pipelines, you're probably using the docker-workflow plugin, not this plugin.

This plugin does do garbage collection of docker containers, ensuring that it doesn't leave any that _it_ created hanging around unused, but deciding which filesystem layers and images are or aren't useful to keep in the docker daemon's cache is very much a matter for the docker daemon, not Jenkins.
In addition, any given Jenkins server can't assume that it has sole responsibility for any given docker daemon, or even full visibility of everything that docker daemon does - Jenkins doesn't have the information required to make those decisions (which is why the docker plugin tags all the containers it starts so that it can recognise them later when garbage-collecting containers - we don't want to "collect" someone else's container).

FYI my work colleagues solve this issue at the docker-daemon level.  Jenkins makes sure containers get disposed of properly, and the docker daemons then make sure any unused (and unnecessary) images and filesystem blobs get purged over time as a background activity.

**Comment by brianjmurrell** [comment]
> Firstly, if you're using pipelines, you're probably using the docker-workflow plugin, not this plugin.

OK.  I will check that out.  TBH trying to determine which plugins are in use for different use-cases is a bit difficult for people not familiar with all of the inner workings of Jenkins.  Thanks for the clarification though.

As for garbage collection responsibility, to be clear, I am not referring to the clean up of unused Docker "filesystem layers".  Of course that is up to Docker to manage.

What I am referring to is *final* images.  Of course Docker can't know which images that a user (or a tool on behalf of a user, such as Jenkins) would consider garbage and which he doesn't want.  That is up to the user (or, again, the tool, acting on the user's behalf) to decide.

The problem is that for as many times as the Dockerfile for a given pipeline job gets modified, Jenkins creates a new Docker image for it, making the image for the previous iteration of of that job's Dockerfile obsolete.  But Jenkins doesn't remove that obsolete image.  The result is that images pile up and pile up as Dockerfiles are modified.

But from Docker's perspective, they are all valid, usable images.  There is no way it could know that the previous iterations of a Jenkins pipeline job are now garbage.  Only Jenkins knows that because it created a new one to be used in preference to the old one, which it didn't delete.

Furthermore, the tags of the images don't make it all (even slightly) obvious which images that Jenkins has created are for which iteration of which pipeline job.

And this one is squarely on Docker, but Docker doesn't tell you the last time an image was **used**.  There are tickets open on that, but frankly that doesn't absolve Jenkins of cleaning up it's garbage, IMHO.

But if what I am using is indeed the docker-workflow plugin, not this plugin, then I need to take this issue there.

Much thanks for the response and pointer.
