### ISSUE TITLE
Unable to connect to docker container in hostmode

### ISSUE THREAD

**Issue by kubinski** [jenkinsci/docker-plugin#725]
- Docker plugin 1.1.3
 - Jenkins 2.150.2
 - Docker 18.06.2-ce

I have a docker cloud configured and in the configuration I specify that the network mode is host and in the connect method specify ssh on a specified port (say 30022). My docker container is successfully started by jenkins when I run a job on that cloud and my container starts its own sshd with port 30022 exposed.  I can verify that ssh is open and properly exposed by ssh'ing into the container over said port.

I haven't traced all the logic on how the plugin works but it doesn't seem to care what port I specified in the connect method but instead seems to rely on inspection of the docker container to see what ports are bound.  This inspection fails because in network mode there are no bound ports and hence a NullPointerException is thrown.

This exception is thrown in the DockerComputerSSHConnector.getBindingForPort method.

**Comment by pjdarton** [comment]
Yup, the SSH connection logic in the plugin asks docker where the container's port is exposed.  It was never intended to work with more restrictive networking situations, which is why it doesn't.

If you want to have your container set up so that it has host-only network connectivity then the SSH connection method isn't going to work for you, at least not unless you want to enhance the plugin to support that ;-)
Try using the direct-attach connection method instead - that only requires that Jenkins is able to communicate to the docker daemon and doesn't care about the network setup of the container.
Note: There was a bug in the direct-attach connection method which made it unreliable prior to version 1.1.6.  Best upgrade to version 1.1.6.
