### ISSUE TITLE
New option for using the build slave name as container name

### ISSUE THREAD

**Issue by pcavezzan** [jenkinsci/docker-plugin#735]
This feature is pretty similar to the issue #404 

With my team, we use docker to run containers as build slave thanks to this awesome docker plugin.

It runs perfectly fine but as we would like to monitor those building containers slave, we think it would be nicer to lookup directly to the slave thanks to their names as container name.

Right now, we surely can monitor them but to get to the right running container, we need to:
1) get the slave name generated 
2) go to Docker admin page to look at the lookup table displaying the running containers
3) search and find for the container ID associated to the running slave
4) go to our monitor dashboard to look at the differents stats for the docker container thanks to the ID

In our situation, it would be much simplier to :
- directly get the slave name generated
- go to our monitor dashboard to look at the differents stats for the docker container thanks to the name

I wrote this new optional feature (and will open a PR) with a simple checkbox (by default, unchecked to keep the actual docker plugin behavior).
If the checkbox is checked, then we run the container with the same name as the slave name generated. 
This should not be a problem as the docker slave name is generated with a unique name.

**Comment by pjdarton** [comment]
To be honest, I'm not keen on having Jenkins specify container names :-/

FYI a number of users (including me) previously hit problems with this plugin precisely because any name generated by Jenkins cannot be guaranteed to be unique within a given docker daemon.
Jenkins only knows its own slave names; when you have a docker daemon (or docker swarm) that's shared between multiple Jenkins instances (as numerous folks do) then you can get multiple Jenkins instances all choosing to use the same name, causing a naming-collision and then you get failures.
To ensure unique container names within a docker daemon, you _have_ to leave it up to the docker daemon to choose them.

However, because users (such as yourself) _also_ want to be able to go poking inside containers, the plugin sets labels that contain lots of useful meta-data; this includes the Jenkins instance's ID, its URL, and (as you want) the name of the Jenkins slave within that Jenkins instance.

Personally, I think it'd be easier to make the container name easily available from the slave node page.
The slave node page already tells you "Docker container <container-ID> on cloud <docker-cloud-name>" - I _suspect_ that it would be relatively simple (and non-invasive) to make cosmetic enhancements to include the container name (as well as the ID) on that page.

**Comment by pcavezzan** [comment]
Hi @pjdarton ,

I hope you're doing well !
Sorry for my late answer, quite busy this couple of days...

Yes, your idea to add the container name in the sentence is great :

<ID_CONTAINER> on Cloud xxxx
like 
<ID_CONTAINER> with name <container_name> on Cloud xxxx

I agree, it would be easier and certainly avoid the risk of collision name 👍 

So we can forget about the optional checkbox and add this information because my only need is to get a way to identify quickly a potential container slave build for build project. In this page, with the id and name, it would definitely feed my need. 

I will work on this and get back to you with the right change for my PR 😄as soon as i get the time (certainly in the middle of next week)

**Comment by pjdarton** [comment]
No worries - been quite busy myself ;-)

FYI I'd recommend that you take a look at the vSphere and/or OpenStack plugins and take a look at how those plugins display their slave-node information.  It would be good if the docker-plugin was made cosmetically similar in style.
My guess is that the "one long line of text" method used by the existing docker-plugin code is likely to look intolerably ugly once we add "container name" into the mix, so switching to the method used by the vSphere and/or OpenStack plugins is a good option (and there's no reason to stop with just the container name - there's all sorts of potentially useful information that could be included here ... just as long as it's not potentially security-sensitive information)
