### ISSUE TITLE
disable automatic kill docker slave container

### ISSUE THREAD

**Issue by f2rozen541** [jenkinsci/docker-plugin#746]
I want reuse docker container, so I dont want docker slave to be killed when jenkins job finished. Is there any solution?

My problem comes here. My jenkins job takes too long time at pulling code from git remote repo.  And default docker plugin will delete the containers when job finished. So I cant reuse the workspace. So I want to reuse docker slave when finish its job.

and my jenkins version is 2.113. docker plugin version is 1.1.7.

**Comment by pjdarton** [comment]
Not directly.

The entire purpose of *this* Jenkins plugin (`docker-plugin`) is to provide one-shot containers that are used once before being destroyed automatically.  That's what it's designed to do, and there isn't support for anything other than that - the use of a "use it once then throw it away" Jenkins "retention strategy" is hard-coded behavior.
In theory, it would be possible to enhance the plugin to support other retention strategies, e.g. a "keep it until it's been idle for more than half an hour" strategy, but nobody's coded that ... and it's unlikely to be a good solution for the problem you're facing anyway as it'll still throw away the containers (and their contents) if you stopped causing builds all the time.

I'd suggest you try two things:
1. Tell git to do a "shallow" clone.
It's in the git options (it's fairly well hidden).  Where I work, I found that the difference between a "full" clone and a "shallow" clone was the difference between 15 minutes and 5 seconds when the network was poorly.  Most CI builds only need "the latest code" so there's no benefit for fetching the entire history - that's what "shallow" does.  Just set the "depth" to 1 or more so Jenkins see's _some_ history, otherwise it won't know what changed between one build and the next (but a shallow clone with depth of 10 is still _way_ faster than a full clone).
1. Make a writable folder on your docker host and cross-mount that into your docker containers.
Where I work, we had similar issues with mvn downloads (and an in-house equivalent) so I made a writable directory on my docker host server(s), specified (in the docker template) that it should be mounted into the docker containers, and then (inside the container) symlinked from where mvn etc was going to cache downloads to point to where I'd mounted the directory, giving me download caches that were shared between containers (and hence between builds).
We did have to take steps to ensure that anything using these shared folders would cope with having other processes read/write to it at once but, once that was made stable, our builds only ever downloaded things once as future builds used the cached copy.

You could also investigate having a shared docker volume that's reused between containers.  There's a tick-box on the Jenkins config that says whether or not volumes should be deleted when the container is deleted, and so you'd need to ensure that's not ticked, but that's another option.  You'd probably need to make your own custom docker image with persistent volumes in specific places (e.g. `/home/jenkins/agent/workspace/yourJobName/.git`) to make that work tho'
