### ISSUE TITLE
Configurable number of executors

### ISSUE THREAD

**Issue by javierlopezfernandez** [jenkinsci/docker-plugin#81]
Our test jobs normally chain other jobs. For that reason we require more than one executor per slave. Looking at the code I see numExecutors is hardcoded to 1 and I wonder if this is temporal or permanent feature

**Comment by maafy6** [comment]
I'm going to throw in my lot by saying this would be pretty useful, although I don't claim the same use case that the OP has, I just want to be able to run multiple builds on the same slave.

It's not entirely true that spinning up multiple containers is the same as (or even some epsilon less than delta than) multiple executors in the same container. There is a decent overhead in launching a container, having the jar copied over, doing the handshake with the server, yada yada yada. If you have the same issue as several others have reported of slave containers being stuck in suspended mode, you can have a fair amount of churn waiting for a container that works, and when that happens, you want to milk it for all it's worth.

Even if you do have mostly successful containers, I've found it pretty easy to DOS myself with a job that has about 20 sub-jobs, each of which were spinning up containers to do their build. Even with caps (instance and total), it was about a 50-50 shot as to whether or not I'd have to give up and restart Jenkins because it couldn't handle the churn.

I hacked the changes in the above commit together to test on our system here and it's working much, much smoother. I'm not 100% interested in opening a pull request right now because the version that that's based off of is fairly old, and I haven't been bothered to figure out what I need to do to build with the new docker-java jar the pom mentions because it can't seem to find it, but that's the base. It mostly merges straight into the current master (one files had some imports rearranged, but that was the only real conflict).

**Comment by KostyaSha** [comment]
experimental feature in master, try follow references too many duplicated issues..

**Comment by mikemol** [comment]
> Probably permanent, because I can't see the use of >1 executor per docker slave.

I realize that this may or may not be particularly relevant to this specific issue, but in Openshift, when namespace quotas are enabled, you can only get so much CPU or memory available for your pods and containers. And, for some setups, you _must_ set up quotas and CPU/memory commits for each pod, which means you can't rely on an idle container leaving cycles or resources for another container to use; a container effectively has 100% utilization of its quota at all times.

I realize this is a terrible setup, and systems probably shouldn't be set up that way, but it happens, and it's not always under our control. As such, in order to be able to do effective resource sharing, the only way to do it in such as case is _inside_ the container, and the only way to do that here is with multiple executors to an agent.

**Comment by pjdarton** [comment]
If containers are run with the "docker once" strategy where they are discarded immediately after completing any form of build activity then you _can't_ have more than one executor (because the first one to finish would kill all of them).

If you were to implement this feature, you'd have to implement a different retention-strategy, e.g. a "until it's been left idle for too long" strategy (as used by the OpenStack plugin etc) and then you could have more than one executor ... although that would be removing most of the advantages to having "one-use disposable" containers because you then couldn't be sure your builds were starting with a clean environment (just as with static slaves).

It would be much better to run more than one container.  Docker is very good at allowing memory re-use so you should find that N containers each having 1 executor have a very similar resource usage to 1 container with N executors.

**Comment by mikemol** [comment]
To be clear, I deal with the clean-workspace issue with a 

```
node() {
  cleanWs(disableDeferredWipeout: true, deleteDirs: true)
  try {
    // do work
  } finally {
    cleanWs(disableDeferredWipeout: true, deleteDirs: true)
  }
}
```
pattern, implemented as a utility function that takes a closure as an argument. So, roughly (you'd need to modify to pass in parameters managing `node()`'s arguments):

```
def wsWrap(Closure body() ) {
  def res
  node() {
    cleanWs(disableDeferredWipeout: true, deleteDirs: true)
    try {
      res = body()
    } finally {
      cleanWs(disableDeferredWipeout: true, deleteDirs: true)
    }
  }
  return res
}
````  

It only leaks occasionally, and then only when communications between the agent and the master are totally fouled up. But `idleMinutes` usually steps in and cleans things up when that happens...and the initial `cleanWs()` prevents it from being anything more than a storage leakage problem.

**Comment by pjdarton** [comment]
In simple cases, sure, having a clean workspace is all you need to worry about.  In my experience, I've found that my developers can get "inventive" when it comes to making a mess that they can't tolerate starting with :grin: 
That's why I like one-use disposable containers.

However, regardless of the reasons, the underlying issue remains the same - this plugin (currently) only supports having a "one-use" retention strategy and, if you want multiple executors, this plugin would need something more complex.  If you're interested in doing that, take a look at the [CONTRIBUTING.md](https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md) guidelines.
