### ISSUE TITLE
NPE while using host network mode for docker

### ISSUE THREAD

**Issue by chintanb** [jenkinsci/docker-plugin#815]
Upon switching the network mode to `host`, I am getting NPE when Jenkins tries to provision the containerized agent. 
Works fine if I dont specify in network mode (ie. default it to bridge mode).

I tried exposing a port from the dockerfile and added a mapping too, but still same error.

 - Plugin Version 1.2.1
 - Jenkins version = LTS 2.249.2
 - Docker Version = 19.03.13, API Version = 1.40

**Stacktrace** 

```
Error in provisioning; template='DockerTemplate{​​​​​​​​configVersion=2, labelString='LabelString', connector=DockerComputerSSHConnector{​​​​​​​​sshKeyStrategy=InjectSSHKey{​​​​​​​​user='root'}​​​​​​​​, 
port=22, launchTimeoutSeconds=10, retryWaitTime=5}​​​​​​​​, 
remoteFs='/home/jenkins', instanceCap=1, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@29, dockerTemplateBase=DockerTemplateBase{​​​​​​​​image='<artifactory-url>?/<image-name>:latest',
pullCredentialsId='***', network'='host', volumes=[<volumes>], bindAllPorts=false, cpuPeriod=0, cpuQuota=0, privileged=false, tty=false, extraHosts=[<host-url>]}​​​​​​​​, removeVolumes=false, stopTimeout=0, pullStrategy=PULL_LATEST, pullTimeout=300, 
nodeProperties=[hudson.slaves.EnvironmentVariablesNodeProperty@43b59685, hudson.tools.ToolLocationNodeProperty@65ec2073], disabled=BySystem,0 ms,4 min 59 sec,Template provisioning failed., name='<name>'}​​​​​​​​' for cloud='<cloud>'
java.lang.NullPointerException
	at io.jenkins.docker.connector.DockerComputerSSHConnector.getBindingForPort(DockerComputerSSHConnector.java:335)
	at io.jenkins.docker.connector.DockerComputerSSHConnector.createLauncher(DockerComputerSSHConnector.java:292)
	at io.jenkins.docker.connector.DockerComputerConnector.createLauncher(DockerComputerConnector.java:135)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.doProvisionNode(DockerTemplate.java:731)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:676)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:375)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pjdarton** [comment]
"it shouldn't do that"...
The faulty code is at [DockerComputerSSHConnector.java:335](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.2.1/src/main/java/io/jenkins/docker/connector/DockerComputerSSHConnector.java#L335).
I guess that the previous statement `final Ports.Binding[] sshBindings = bindings.get(sshPort);` returned null, which it'll do if the dockerjava code tells it that there aren't any bindings to port 22 (or whatever `sshPort` is).
Obviously, there should always be a binding to the SSH port, so it's not clear why we're being told otherwise.

I agree that the handling is messy (IMO code should not NPE, it should throw a nicer exception if it has to throw at all) and that could be easily tidied up so we got a better exception.
... but I don't believe that tidying it up would make things work in your situation because we're being told (by the dockerjava library) that there's no SSH port exposed by the container.  I've not checked but I'd guess it's telling us this on the assumption that exposing a port on a "host only" network isn't going to any use to anyone ... and I guess that, in your specific use-case, your Jenkins has access to this host-only network so it will be useful in your case.
i.e. the dockerjava code `InspectContainerResponse.getNetworkSettings().getPorts().getBindings()` wasn't designed with your use-case in mind.

i.e. I agree it's a bug and it wouldn't be too difficult to make it throw a nicer exception in this circumstance, but it'd be non-trivial to cater for your use-case.

So... unless you fancy having a go at fixing it yourself (and I would welcome a PR that does this, and a PR throwing a better exception for that matter too), I'd suggest you switch to using the "Attach" connection method - that's far more suited to this use-case where Jenkins & the containers are very close (from a network p.o.v) and it's much more efficient than layering things over an SSH connection.
(FYI, IMO Attach is simplest, JNLP is good, and SSH is best reserved for situations where it's the only option due to network limitations; sadly folk tend to gravitate to SSH by default because it's familiar)

**Comment by chintanb** [comment]
@pjdarton that seems to have done the trick.
Thanks for the prompt reply and yeah the meaningful error message would definitely help here but I think this bug will serve as documentation for people like me.
