### ISSUE TITLE
Jenkins was unable to connect to the docker dynamic slave node

### ISSUE THREAD

**Issue by ktpktr0** [jenkinsci/docker-plugin#841]
jenkins version: 2.289.2
docker version: 19.03.9

Follow the tutorial to install the docker plug-in and configure the TCP endpoint on the docker service of the slave node.
JNLP method is used to connect on Jenkins, but the following error occurs:

![image](https://user-images.githubusercontent.com/41657218/126736526-33664f7e-5b2a-4fd4-9808-48a0ea416621.png)

master与slave主机的防火墙未开启
![image](https://user-images.githubusercontent.com/41657218/126736609-dcd0ff7c-5d74-4011-acf0-91db25b15857.png)

![image](https://user-images.githubusercontent.com/41657218/126735554-6dc85201-3af4-4e1c-97bd-4a15b0645a0d.png)

**Comment by pjdarton** [comment]
I'm not sure what tutorial you're referring to, but that stacktrace says `java.lang.RuntimeException: Failed to serialize io.jenkins.docker.DockerTransientNode#acceptingTasks` so, as that field is an `AtomicBoolean` which is part of the JVM, my _guess_ is that you've got a JVM mismatch between the JVM you're running on the Jenkins main instance and the JVM inside the docker image you're specifying (`jenkins/inbound-agent:4.-1`)

I'd suggest you go back to whoever wrote that tutorial and tell them they've got it wrong.

Also, tell them that the term "slave" was deprecated many years ago - that's why it's called an "inbound agent" rather than a "inbound slave".
