### ISSUE TITLE
Typo error on README.md

### ISSUE THREAD

**Issue by rahuldimri** [jenkinsci/docker-plugin#916]
### Describe your use-case which is not covered by existing documentation.

favorite spelling mistake on the document.

**Comment by MarkEWaite** [comment]
Not a spelling mistake, rather a choice that the Jenkins project generally uses the American spelling of "favorite" rather than the British spelling of "favourite".  See www.jenkins.io and [plugins.jenkins.io](https://plugins.jenkins.io/ui/search?sort=relevance&categories=&labels=&view=Tiles&page=1&query=favorite) for examples

**Comment by rahuldimri** [comment]
Got it thanks for letting me know !!

**Comment by pjdarton** [comment]
FYI, according to my professional documentation colleagues, if you show various folks those two spellings, most UK-English will recognise "favorite" as the USA spelling and "favourite" as the (correct!) English spelling, most who speak/write English non-natively will accept either spelling ... but far too many US-American speakers will vociferously claim that "favorite" is the one and only correct English spelling.
This means that when we're writing documentation for a global audience, we have to write in American-English in order to avoid a deluge of complaints about spelling (and we also have to claim we're writing in "English" because the American name for the American language is "English", not "American" 😝)
(which is why the UK and USA are often described as "two nations divided by a common language" 😁)

...however, personally speaking (as a native of England, who was brought up speaking _English_ English), I really appreciate you taking the time to try to correct the American mis-spelling; thank you 👍
