### ISSUE TITLE
Add support for ssh:// scheme

### ISSUE THREAD

**Issue by kuoruan** [jenkinsci/docker-plugin#938]
### What feature do you want to see added?

As docker docs say, https://docs.docker.com/engine/security/protect-access/#use-ssh-to-protect-the-docker-daemon-socket

ssh protocol is support to connect remote docker

but I can not use it now.
```
Unsupported protocol scheme: ssh://docker@10.10.1.2
```

**Comment by basil** [comment]
Tracked upstream as https://github.com/docker-java/docker-java/issues/1130; implemented in https://github.com/docker-java/docker-java/pull/1440 which was rejected. The code lives on in a third-party module at https://github.com/mwiede/docker-java-transport-jsch, but I do not feel comfortable integrating that into `docker-java-api`, since it is not part of the main `docker-java` package. In any case, I am closing this PR since it was filed under the wrong component: this is a `docker-java-api` issue, not a `docker-plugin` issue.
